# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: cd src; go test -race; cd ..

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
